import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[font]
size = 14.0

[font.normal]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Regular"
